describe('spec', () => {
    it('pdp', () => {
      cy.visit('http://169.61.105.110/medicareAdvantage_sandbox/landing-page')
      cy.get('#mat-input-0').type('testuser@gmail.com')
      cy.get('#mat-input-1').type('user123')
      cy.get('.mat-focus-indicator').click()
      cy.get('.fontSize20px').should('have.text','Your Medicare Options') //assertion
      cy.get('.button-container > .mat-focus-indicator > .mat-button-wrapper').click()
      //cy.get('#mat-radio-11 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click()
      cy.get('.form-field-container-col2 > :nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').type('sneha@gmail.com')
      cy.get('#mat-input-4').type('sneha')
      cy.get(':nth-child(5) > :nth-child(1) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').click()
      cy.get('.mat-datepicker-toggle > .mat-focus-indicator').click()
      cy.get(':nth-child(6) > [data-mat-col="2"]').click()
      cy.get('.mat-calendar-body-active').click()
      cy.get('#mat-input-8').type('33408')
      cy.get('.mat-form-field-suffix > .mat-focus-indicator > .mat-button-wrapper > .mat-icon').click()
      cy.get('#mat-select-10 > .mat-select-trigger > .mat-select-arrow-wrapper').click()
      cy.get('#mat-option-19 > .mat-option-text').click()
      cy.get('#mat-input-9').type("sneha@gmail.com")
      cy.get('#mat-input-10').type('7327456766')
      cy.get('.form-wrapper > .mat-raised-button > .mat-button-wrapper').click()
      cy.get('#mat-radio-14 > .mat-radio-label > .mat-radio-container > .mat-radio-outer-circle').click({force:true})
      cy.get('.preference-wrapper > .button-wrapper > .mat-focus-indicator').click({force:true})
      cy.get(':nth-child(1) > .login-form-forgot > u').click()
      cy.get('.ant-select-selection-item').type('s')
      cy.get('.ant-select-item-option-content').click()
      cy.get('.ant-drawer-body > :nth-child(4)').click()
      cy.get('.ant-drawer-footer > div.ng-star-inserted > :nth-child(2)').click()
      cy.get('.ageRatedScrollPopup > .marginLeft20pxImp').click()
      cy.get('.textAlignLeft').click().clear().type(1)
      cy.get('.marginTop2Percent > .ng-star-inserted').click()
      cy.get('.ng-star-inserted > .mat-focus-indicator').click()
      cy.get('#mat-checkbox-2 > .mat-checkbox-layout > .mat-checkbox-inner-container').click()
      cy.get('.selected-pharmacy > .button-wrapper').invoke('css', 'position', 'fixed').click();
      cy.get(':nth-child(5) > .mat-focus-indicator').click()
      cy.get('#mat-checkbox-13 > .mat-checkbox-layout > .mat-checkbox-inner-container').click()
      cy.get('.fixed-bottom-1 > .button-container').invoke('css', 'position', 'fixed').click()
      cy.get('.selected-container > :nth-child(1) > .mat-focus-indicator').click()
      cy.get('#mat-checkbox-26 > .mat-checkbox-layout > .mat-checkbox-inner-container').click()
      cy.get('.fixed-bottom-1 > .button-container').invoke('css', 'position', 'fixed').click()
      cy.get('#mat-checkbox-39 > .mat-checkbox-layout > .mat-checkbox-inner-container').invoke('css', 'position', 'fixed').click({force:true})
      cy.get('.fixed-bottom-1 > .button-container > :nth-child(1)').click()
      cy.get('.button-wrapper > :nth-child(1)').click({force:true})
      cy.get('.button-container > :nth-child(2)').invoke('css', 'position', 'fixed').click({force:true})
      cy.get('.button-wrapper > .ng-star-inserted').click()
      cy.get('.button-wrapper > :nth-child(1)').click()
      cy.get('.nav-link').click()
      
    


      
    })
  })