// pharmacypg.clickBackBtn()
   // cy.wait(3000)
    //drugselect.clickDoneaddingdrug()
    //cy.wait(30000)
   // pharmacypg.checkZipRadio()
    //cy.wait(3000)
   // pharmacypg.enterZipcodePharmacy('wallgreens')
    //cy.wait(10000)
    //pharmacypg.clickFindPahramcyinzipcode()
    //cy.wait(2000)
    //pharmacypg.clickPharmacyagain()
    //cy.wait(1000)